manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: krikun98
      url-base: https://github.com/krikun98
    - name: mouse-3.2
      url-base: https://github.com/urob/zmk/tree/mouse-3.2
  projects:
    - name: zmk
      remote: mouse-3.2
      revision: mouse-3.2
      import: app/west.yml
  self:
    path: config
